[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:server]
command=node /app/apps/server/dist/index.js
directory=/app/apps/server
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
environment=NODE_ENV="production",PORT="4000"

[program:web]
command=node /app/apps/web/node_modules/.bin/next start -p 3000
directory=/app/apps/web
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
environment=NODE_ENV="production",PORT="3000"
